### ISSUE TITLE
Instead of [[document-header]] "1" in document

### ISSUE THREAD

**Issue by mamuerie** [ClaudioZandonella/trackdown#17]
Hi Team-Trackdown, 
first of all thank you for this great tool! It is exactly what I was looking for and what I need to collaborate with my co-authors who don't want to work with RMarkdown!
Unfortunatelly, I have a bug with the document header. After uploading the file, there is a 1 in the google drive document instead of the flac [[document-header]] and accordingly the header could not be restored in RStudio. It works perfectly fine for the code chunks, though. 
Does anyone have any idea what is going wrong here and how to fix it? Thanks a lot in advance!

**Comment by ClaudioZandonella** [comment]
Hi @mamuerie,

We are really happy that you find `trackdown` useful for your work. 

Unfortunately, the bug you have reported is really strange. 
Do you mind sharing the header and the first few lines of your `.Rmd` document? This will allows us to evaluate what caused the problem.
And also, which operative system do you use? Different character encoding between OS sometimes triggers some problems. 

For a quick solution to the problem:
- When downloading the file from google drive with the `download_file()` function, if `trackdown` fails to retrieve the `[[document-header]]` tag, the code is automatically restored at the first line of the document. Was the code not restored at the first line in your case? The following message is printed in the console:
``` 
Warning message:
Failed retrieving [[document-header]] placeholder, code added at first line 
```
- Alternatively (a little bit raw 😅), you could simply add "[[document-header]]" in the document on google drive, on a new line right after the instructions. This should be enough for `trackdown` to correctly retrieve the tag when downloading.

**Comment by mamuerie** [comment]
Hi @ClaudioZandonella,
thanks for your fast response! I tried it today on my private computer (both are windows machines) with the latest RStudie and R Version and there it worked perfectly fine. So it seems that it is somehow related to that. Sorry that I did not try this before I asked here!

**Comment by weiyangtham** [comment]
Hi, really excited about this package but just wanted to add that I'm having this problem too. This is the header I have in my `.rmd` document. I'm using Mac OS (Big Sur). Adding "[[document-header]] at the top of the Google Doc doesn't seem to help either. 

`---
title: "Untitled"
author: "Wei Yang Tham"
date: "8/24/2021"
output: html_document
---`

**Comment by dfranquesa** [comment]
@ClaudioZandonella  I can not say the say as @weiyangtham 
Still not works for me.
I've update to Version: 1.0.1,  2021-08-28 15:04:24 
Please find attached a zip file with all the info I think you are asking for debugging.
I'm using Ubuntu, I've add also the session_info.html.
Thanks!
David
[Debugging-issue-17-DFG.zip](https://github.com/ClaudioZandonella/trackdown/files/7070926/Debugging-issue-17-DFG.zip)

**Comment by ClaudioZandonella** [comment]
Hi @dfranquesa,

thanks for your help!

Looking at your `session_info.html` I see
`##  V trackdown           * 1.0.0      2021-08-28 [1] Github (claudiozandonella/trackdown@9445154)`
with
`##  V ── Loaded and on-disk version mismatch.` 

Probably you installed the new version of the package but tho old one was still loaded. Maybe restarting the rstudio session will solve the issue. You need the version `1.0.1` to be loaded. 

To be sure that the new version is loaded you can run the following commands
```
name_your_file <- "bug_trackdown_header.Rmd"   # path to your file
original_text <- readLines(name_your_file)
info_patterns <- trackdown:::get_extension_patterns("rmd")
head_info <- trackdown:::extract_header(original_text, info_patterns)
str(head_info)
```

the result should be

```
'data.frame':	1 obs. of  4 variables:
 $ starts     : int 1
 $ ends       : int 6
 $ header_text: chr "---\ntitle: \"Analysis Script\"\nauthor: \"David Franquesa, Mireia Roura, Leandro Navarro\"\ndate: \"`r format("| __truncated__
 $ name_tag   : chr "[[document-header]]"
``` 

If `header_text` and `name_tag` are type `chr` the new version is working. Instead, if they are still type `factor`, the old version is working.

Again, thanks for your help!
Claudio

**Comment by dfranquesa** [comment]
You are right! uauuu! it works now, thanks!

**Comment by ClaudioZandonella** [comment]
Thank you all for your help!

Anyone who finds the same issue, please, install the package version v.1.0.1 from GitHub with 

```
# install.packages("remotes")
remotes::install_github("claudiozandonella/trackdown",
                         build_vignettes = TRUE)
```
