### ISSUE TITLE
[BUG] typo in vignette

### ISSUE THREAD

**Issue by daaronr** [ClaudioZandonella/trackdown#23]
In the workflow [vignette](https://claudiozandonella.github.io/trackdown/articles/trackdown-workflow.html)

> You create the initial document, for example My-Report.Rmd, and upload the file to Google Drive using the function upload_file():

`trackdown::update_file(file = "Path-to-file/My-Report.Rmd", hide_code = TRUE)`

I think you mean `upload_file` here?

**Comment by ClaudioZandonella** [comment]
Thanks, @daaronr for spotting this typo!

Now it is fixed in the vignette and online documentation.

**Comment by daaronr** [comment]
Great. Loving trackdown so far. It solves a major problem

**Comment by ClaudioZandonella** [comment]
We are very happy you enjoy trackdown. We really hope it could help everyone in their own daily work 😁
