### ISSUE TITLE
Rewrite of `rmdrive`

### ISSUE THREAD

**Issue by januz** [ClaudioZandonella/trackdown#4]
Thanks so much for writing this package, @ekothe! I was very happy to find it when I started thinking about how to implement a workflow that allows collaborative editing of `.Rmd` files on Google Drive. I have since modified a fork of @benmarwick's fork of this repository: https://github.com/januz/rmdrive.

I rewrote the package with a specific workflow in mind that I describe in the `Readme`. As this approach is relatively specific, I was wondering whether you would still want me to prepare a pull request here or just have the two packages evolve independently. Some of my changes might be of general interest though like allowing for the use of Team Drives and (sub)folders on Google Drive. Please let me know whether you'd be interested in me preparing a PR for a subset of my changes. Thanks!

**Comment by ekothe** [comment]
@januz I think the workflow you describe is reasonably similar to the workflow I'd want to use if using this package (although I think you've articulated it much more clearly than I had). I'd be happy to incorporate your change into rmdrive but I am concious that you've put a lot of work into essentially rewriting the package from scratch and implemented a lot of things this (very simple) implementation did not - so if you want to continue seperately I have no issue with that

**Comment by januz** [comment]
@ekothe I am fine with either approach as well. I haven't implemented any changes in a while but was just made aware that my rewrite does not work properly on Windows machines (I assume the deletion of additional linebreaks that GoogleDrive adds). So I will want to address this issue when I find some time. I also had ideas for additional features like having a hidden folder that stores versions of the local `.Rmd` file if the GoogleDrive document has changed and would overwrite the local document (to not lose local changes that hadn't been sent to GoogleDrive yet).

I just saw that @ClaudioZandonella built upon my rewrite to implement more features. Maybe we should all get together to decide on where `rmdrive` should live in the long run and whether we want to develop it collaboratively (would probably be better to have different forks evolve and leave users confused as to which one to choose). What do you think?
