### ISSUE TITLE
Clarify scopes needed for the app in the vignette

### ISSUE THREAD

**Issue by maelle** [ClaudioZandonella/trackdown#43]
In the vignette about OAuth setup, at the moment only the non sensitive scopes are shown because the Google Drive and Google Docs APIs are enabled after that step. Could there be a screenshot of the sensitive scopes as well? Thank you!

**Comment by ClaudioZandonella** [comment]
Hi @maelle,

Thanks for pointing out this issue. I slightly changed the order of the guide.
Now, the activation of Google APIs comes first and then the scopes are enabled.
In this way, it is also possible to activate the sensitive scopes and I added a screenshot listing all the enabled scopes.

Doing that, I actually noted that enabling scopes is not required to obtain the 'OAuth 2.0 Client IDs. For setting up the OAuth procedure, we only need to activate the 'OAuth consent screen'.

Enabling sensitive scopes is only required during the verification of our newly created app by Google. However,  we can use the credentials of the newly created app without the need to proceed to the verification by Google. In this case, we are limited to 100 users, but it should be more than enough for personal usage.

Anyway, I leave the activation of sensitive scopes in the guide. In this way, the guide is more complete. I only hope users will not be intimidated by the word 'sensitive scopes'😅

**Comment by maelle** [comment]
Thank you!!

> I only hope users will not be intimidated by the word 'sensitive scopes'sweat_smile

To be fair, 2FA is probably intimidating on its own but your vignette full of screenshots is very clear!
