### ISSUE TITLE
Add alternative text to vignette images?

### ISSUE THREAD

**Issue by maelle** [ClaudioZandonella/trackdown#45]
For reference https://axesslab.com/alt-texts/ and https://www.w3.org/WAI/tutorials/images/informative/

**Comment by ClaudioZandonella** [comment]
Hi @maelle,

Thanks for the suggestion. I did not know about the alt text features, it is really interesting.

I added alt-text to all figures (and videos) in the package documentation. I hope not it is more inclusive😉
