### ISSUE TITLE
use Markdown roxygen2

### ISSUE THREAD

**Issue by maelle** [ClaudioZandonella/trackdown#51]
I'll make a PR in a sec.

**Comment by maelle** [comment]
Right, good catch!

**Comment by maelle** [comment]
so weird that merging the PR didn't close this automatically :thinking:

**Comment by maelle** [comment]
oh not weird at all, it hadn't been merged to the default branch, it makes sense. :relieved:

**Comment by ClaudioZandonella** [comment]
Yes sorry, I always merge first in the develop branch and then merge in the master.

Do you suggest merging directly in the master is a better approach?

**Comment by maelle** [comment]
@ClaudioZandonella no, any git workflow is fine! I'm more used to merging to the default branch, that's all.
