### ISSUE TITLE
use lifecycle to mark experimental arguments?

### ISSUE THREAD

**Issue by maelle** [ClaudioZandonella/trackdown#53]
With #52 one cannot use `[experimental]` as it indicates a link in Markdown syntax. I replaced it with `(experimental)`.

Alternative: https://lifecycle.r-lib.org/reference/badge.html

**Comment by ClaudioZandonella** [comment]
Hi @maelle,

Thank you for the suggestion! I added the lifecycle badges! they are soo cool❤️
