### ISSUE TITLE
Small typo: donwloaded instead of downloaded

### ISSUE THREAD

**Issue by jajberni** [ClaudioZandonella/trackdown#56]
Congratulations on this package that makes the RMardown collaboration a reality! 

Here is a small typo:
https://github.com/ClaudioZandonella/trackdown/blob/8a4806370639d2028d2a7b48ac373d575dc62eec/R/files_manager.R#L420

**Comment by ClaudioZandonella** [comment]
Hi @jajberni thanks for spotting the typo!

and thank you @krlmlr for the pull request

I merged everything in the new release.

Sorry for the long time it took me to get back on the development, next time i will be faster 😅
