### ISSUE TITLE
Test roundtrip

### ISSUE THREAD

**Issue by krlmlr** [ClaudioZandonella/trackdown#61]
If there is no file on the Google Drive, I would find it useful if trackdown performed a no-op roundtrip: reimport the unchanged document so that any bogus changes are weeded out right in the beginning.

Example: any extra newlines before headings are removed by `trackdown::download_file()` . Ideally, when starting work on trackdown, I would commit those changes first, before importing any real edits.

**Comment by ClaudioZandonella** [comment]
Hi @krlmlr,

The idea of a no-op roundtrip is very useful to solve possible introductions of unwanted meaningless changes during upload download🔝.

At the moment, I just fixed the issue of new lines being removed. If there are other inconsistencies I will try to fix them directly in the code. Obtaining the same document when uploading-downloading during a no-op roundtrip is useful to spot other possible issues in the code and fix them.

I close the issue, but if you find other cases with unwanted changes do not hesitate to report them! Next time I will be much faster in fixing them😅

**Comment by krlmlr** [comment]
Thanks. I think the idea of a roundtrip test is still valid, it could be run unconditionally (or optionally) before each upload too, just to be sure.

Roundtrip will matter much more if we take a stab at #36.
