### ISSUE TITLE
rename the default branch to "main"?

### ISSUE THREAD

**Issue by maelle** [ClaudioZandonella/trackdown#64]
Reference: https://www.tidyverse.org/blog/2021/10/renaming-default-branch/ (usethis' helper functions make the change pretty much painless)

The name "main" is becoming the new standard because of negative associations with the name "master".

> The [Internet Engineering Task Force (IETF) points out](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1) that "Master-slave is an oppressive metaphor that will and should never become fully detached from history" as well as "In addition to being inappropriate and arcane, the [master-slave metaphor](https://github.com/bitkeeper-scm/bitkeeper/blob/master/doc/HOWTO.ask?WT.mc_id=-blog-scottha#L231-L232) is both technically and historically inaccurate."

Quote above from https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by ClaudioZandonella** [comment]
@maelle,

Thank you for pointing out this issue. Now the default branch is set to `main`❤️

**Comment by maelle** [comment]
Thank you!!
